# Generated by Django 5.2.17 on 2026-08-16 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('role', models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur')], default='buyer', max_length=20)),
                ('provider', models.CharField(default='console', max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=180)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Défi OTP',
                'verbose_name_plural': 'Défis OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_e164', 'created_at'], name='directory_a_phone_e_cc63ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur')], default='buyer', max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte téléphone',
                'verbose_name_plural': 'Comptes téléphone',
                'ordering': ['-created_at'],
            },
        ),
    ]
