# Generated by Django 5.2.17 on 2026-08-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0005_order_orderitem_notificationdevice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationDevice',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
