# Generated by Django 5.2.17 on 2026-08-23 07:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0009_appnotification_notificationdevice_promotionquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.PositiveBigIntegerField(default=0)),
                ('buyer_contact', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_sales', to='directory_app.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='directory_app.vendor')),
            ],
            options={
                'verbose_name': 'Vente vendeur',
                'verbose_name_plural': 'Ventes vendeurs',
                'ordering': ['-sold_at'],
                'indexes': [models.Index(fields=['vendor', 'sold_at'], name='directory_a_vendor__f6f948_idx')],
            },
        ),
    ]
