# Generated by Django 5.2.17 on 2026-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0010_vendorsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='kind',
            field=models.CharField(choices=[('promotion', 'Promotion'), ('advice', 'Conseil agricole'), ('stock', 'Stock'), ('subscription', 'Abonnement')], default='advice', max_length=30),
        ),
    ]
