# Generated by Django 5.2.17 on 2026-09-19 05:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0013_productfavorite_vendorfavorite_vendorreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpchallenge',
            name='role',
            field=models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur'), ('provider', 'Prestataire')], default='buyer', max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneaccount',
            name='role',
            field=models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur'), ('provider', 'Prestataire')], default='buyer', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('provider_type', models.CharField(choices=[('mecanisation', 'Mécanisation & Labour'), ('location', 'Location de matériel & engins'), ('traitement', 'Traitement phytosanitaire & Pulvérisation'), ('transport', 'Transport & Logistique de récolte'), ('irrigation', 'Forage & Irrigation'), ('main_doeuvre', 'Main d’œuvre & Récolte'), ('conseil', 'Conseil technique & Analyse de sol'), ('autre', 'Autre service agricole')], default='mecanisation', max_length=30)),
                ('intervention_zone', models.CharField(blank=True, help_text='Zones ou localités d’intervention', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, help_text='Présentation du prestataire, machines et matériels disponibles')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True, help_text='Disponible pour de nouvelles interventions')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestataires_valides', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_providers', to='directory_app.locality')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider_profiles', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_providers', to='directory_app.region')),
            ],
            options={
                'verbose_name': 'Prestataire de services',
                'verbose_name_plural': 'Prestataires de services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex. Labour profond au tracteur', max_length=180)),
                ('rate', models.PositiveBigIntegerField(default=0, help_text='Tarif indicatif en FCFA')),
                ('unit', models.CharField(default='par hectare', help_text='Ex. par hectare, par jour, par heure, par voyage', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='directory_app.serviceprovider')),
            ],
            options={
                'verbose_name': 'Prestation proposée',
                'verbose_name_plural': 'Prestations proposées',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='directory_app.serviceprovider')),
            ],
            options={
                'verbose_name': 'Avis prestataire',
                'verbose_name_plural': 'Avis prestataires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['region', 'locality'], name='directory_a_region__8e4ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_type', 'is_active'], name='directory_a_provide_0aa42d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderreview',
            index=models.Index(fields=['provider', 'is_published'], name='directory_a_provide_2ada79_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceproviderreview',
            constraint=models.UniqueConstraint(fields=('provider', 'author'), name='unique_provider_review_by_author'),
        ),
    ]
