# Generated by Django 5.2.17 on 2026-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0014_alter_otpchallenge_role_alter_phoneaccount_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
