# Generated by Django 5.2.17 on 2026-08-22 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory_app', '0006_remove_order_buyer_remove_order_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de conseil',
                'verbose_name_plural': 'Catégories de conseil',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('localite', models.CharField(blank=True, max_length=100)),
                ('culture', models.CharField(blank=True, max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=20)),
                ('type_alerte', models.CharField(choices=[('SAISONNIERE', 'Conseil saisonnier'), ('METEO', 'Alerte météo'), ('RAVAGEUR', 'Épidémie de ravageurs'), ('FORMATION', 'Formation / Événement'), ('GENERALE', 'Information générale')], default='GENERALE', max_length=30)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte agricole',
                'verbose_name_plural': 'Alertes agricoles',
                'ordering': ['-date_debut', '-date_creation'],
                'indexes': [models.Index(fields=['est_active', 'date_debut'], name='conseil_ale_est_act_469bf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contenu', models.TextField()),
                ('resume', models.TextField(help_text='Résumé court pour la carte d’aperçu', max_length=300)),
                ('culture', models.CharField(blank=True, max_length=100)),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('EXPERT', 'Expert')], default='DEBUTANT', max_length=20)),
                ('image_principale', models.FileField(blank=True, null=True, upload_to='conseil/images/')),
                ('image_secondaire', models.FileField(blank=True, null=True, upload_to='conseil/images/')),
                ('temps_lecture', models.PositiveIntegerField(default=3)),
                ('est_epingle', models.BooleanField(default=False)),
                ('est_publie', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nombre_vues', models.PositiveIntegerField(default=0)),
                ('nombre_favoris', models.PositiveIntegerField(default=0)),
                ('produits_associes', models.ManyToManyField(blank=True, related_name='articles_conseil', to='directory_app.product')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='conseil.categorieconseil')),
            ],
            options={
                'verbose_name': 'Article agricole',
                'verbose_name_plural': 'Articles agricoles',
                'ordering': ['-est_epingle', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='AlerteLue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='conseil.alerte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_lues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_lecture'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'alerte'), name='unique_alerte_lue_par_utilisateur')],
            },
        ),
        migrations.CreateModel(
            name='ArticleFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_utilisateurs', to='conseil.article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ajout'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'article'), name='unique_article_favori_par_utilisateur')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['est_publie', 'est_epingle'], name='conseil_art_est_pub_c3b948_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['culture', 'niveau'], name='conseil_art_culture_262e5b_idx'),
        ),
    ]
