# Generated by Django 5.2.17 on 2026-08-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conseil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='temps_lecture',
        ),
    ]
