# Generated by Django 5.2.17 on 2026-08-30 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil', '0003_article_est_premium_conseilsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeArticleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, max_length=7)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conseil.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_article_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation article gratuit',
                'verbose_name_plural': 'Utilisations articles gratuits',
                'constraints': [models.UniqueConstraint(fields=('user', 'article', 'year_month'), name='unique_user_free_article_month')],
            },
        ),
    ]
