# Generated by Django 5.2.17 on 2026-09-07 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil', '0005_articlereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text="Image à insérer dans l'article", upload_to='conseil/content_images/')),
                ('legende', models.CharField(blank=True, help_text="Légende ou description sous l'image", max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans l'article")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_contenu', to='conseil.article')),
            ],
            options={
                'verbose_name': "Image du contenu d'article",
                'verbose_name_plural': "Images du contenu d'article",
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
