# Generated by Django 5.2.17 on 2026-09-07 01:35

import conseil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil', '0006_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_secondaire',
        ),
        migrations.AlterField(
            model_name='article',
            name='image_principale',
            field=models.FileField(blank=True, null=True, upload_to=conseil.models.upload_to_article_image),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.FileField(help_text="Image à insérer dans l'article", upload_to=conseil.models.upload_to_content_image),
        ),
    ]
