# Generated by Django 5.2.17 on 2026-09-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil', '0007_remove_article_image_secondaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
    ]
